config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users
  root to: "users#index"
  resources :items, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :orders

  validates :user_name,               presence: true
  validates :family_name,            presence: true, format: { with: /\A[ぁ-んァ-ン一-龥々ー]/ }
  validates :family_name_kana,       presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name,             presence: true, format: { with: /\A[ぁ-んァ-ン一-龥々ー]/ }
  validates :first_name_kana,        presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :birth_day, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  def index
    @index = Index.includes
  end


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name, :family_name, :first_name, :family_name_kana, :first_name_kana, :birth_day])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @users = User.includes(:user).order('created_at DESC')
  end

  def show
    @users = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :image, :text).merge(user_id: current_user.id)
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.htnl.erb
  <footer id="footer">
    <small>&copy; MurakamiApp.</small>  
  </footer>
<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://coco-factory.jp/ugokuweb/wp-content/themes/ugokuweb/data/5-1-5/js/5-1-5.js"></script>

</body>
</html>

app/views/layouts/_header.html.erb
<header>
  <h1>Parallax header</h1>
  <p>Parallax scroll effect like Twitter. Pure css, javacsript free.</p>
</header>
<main>
	  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi, tempora voluptatum porro. Harum odio, sapiente dicta, eum quidem porro atque quisquam impedit officia ullam minus, laudantium vel eaque doloribus rem.</p>
	  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sequi, tempora voluptatum porro. Harum odio, sapiente dicta, eum quidem porro atque quisquam impedit officia ullam minus, laudantium vel eaque doloribus rem.</p>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Murakami0614App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_footer.html.erb
<body class="body">
<footer id="red">
  <h1 class="text">DMC</h1>
  <h2 class="text2">&copy;	DIMENSIONMC - DESIGNED BY DEN & FLASH</h2>
  <h2 class="text3">-POWERED BY ENJIN-</h2>
</footer>
</body>

app/views/users/_header.html.erb
<header>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'Category', "#", class: "category-list" %></li>
      <li><%= link_to 'Brand', "#", class: "brand-list" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
      <li><%= link_to current_user.user_name, "/users/#{current_user.id}", class: "user-nickname" %> </li>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'Login', new_user_session_path, class: "login" %></li>
      <li><%= link_to 'Signup', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  <div class='search-bar-contents'>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='Search'>
      <button class="search-button">
        <%= image_tag "iconmonstr-search-thin-240.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  </div>
  <h1>MURAKAMI_APP</h1>
  <p>- Wear your favorite clothes and enjoy your life as you like. -</p>
</header>

app/views/users/index.html.erb
<%= render "header" %>
<div class="wrapper">
<body>
  <ul class="top-banner">
    <li class='list'>
      <%= link_to users_index_path(@user) do %>
      <%= image_tag "SAMPLE.png", class: "item-img" %>
      <div class='item-info'>
        <h1 class='item-name'>
          SAMPLE_1
        </h1>
        <div class='item-price'>
          <span>10,000円<br>(tax inc.)</span>
        </div>
      </div>
      <% end %>
    </li>
    <li class='list'>
      <%= link_to '#' do %>
      <%= image_tag "SAMPLE.png", class: "item-img" %>
      <div class='item-info'>
        <h2 class='item-name'>
          SAMPLE_2
        </h2>
        <div class='item-price'>
          <span>10,000円<br>(tax inc.)</span>
        </div>
      </div>
      <% end %>
    </li>
    <li class='list'>
      <%= link_to '#' do %>
      <%= image_tag "SAMPLE.png", class: "item-img" %>
      <div class='item-info'>
        <h3 class='item-name'>
          SAMPLE_3
        </h3>
        <div class='item-price'>
          <span>10,000円<br>(tax inc.)</span>
        </div>
      </div>
      <% end %>
    </li>
    <li class='list'>
      <%= link_to '#' do %>
      <%= image_tag "SAMPLE.png", class: "item-img" %>
      <div class='item-info'>
        <h4 class='item-name'>
          SAMPLE_4
        </h4>
        <div class='item-price'>
          <span>10,000円<br>(tax inc.)</span>
        </div>
      </div>
      <% end %>
    </li>
  </ul>
</body>
  <%# /商品一覧 %>
</div>

app/views/users/show.html.erb
<%= render "header" %>
<div class="wrapper">
<body>
  <ul class="top-banner">
    <li class='list'>
      <%= link_to '#' do %>
      <%= image_tag "SAMPLE.png", class: "item-img" %>
      <div class='item-info'>
        <h1 class='item-name'>
          <%= link_to 'SAMPLE_1', item_path(user.id), method: :get %>
        </h1>
        <div class='item-price'>
          <span>10,000円<br>(tax inc.)</span>
        </div>
      </div>
      <% end %>
    </li>
  </ul>
</body